### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by logankoester** [daxliar/submerger#1]
This looks great for learning languages, but I have another use case:

When I watch TV/movies with my girlfriend she needs Thai subtitles while I need English subtitles, which means that any content spoken in a third language is very difficult for us to enjoy together.

I looked everywhere for a player that could display two subs simultaneously, but after thinking about it I like your solution better.

Looking forward to trying this when I get home!

**Comment by daxliar** [comment]
Thank you very much, I really hope this would help you guys! 
Please let me know in case you find issues!

**Comment by logankoester** [comment]
Will do!
